### ISSUE TITLE
`require': cannot load such file -- slop (LoadError)

### ISSUE THREAD

**Issue by nimi0112** [kesha-antonov/android-sms-verification-hash#1]
Traceback (most recent call last):

``` 2: from /Users/nimish/Downloads/android-sms-verification-hash-master/get_sms_verification_hash.rb:2:in `<main>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- slop (LoadError) ```

I am getting this error. Any possible solutions?

**Comment by nimi0112** [comment]
My bad I resolved it by installing slop from `https://rubygems.org/gems/slop/versions/4.2.1`
